services:
  db:
    image: postgres:15-alpine
    container_name: fitbit-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fitbit_user
      POSTGRES_PASSWORD: fitbit_pass
      POSTGRES_DB: fitbit_db
    volumes:
      - ./.db_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:10.4.18
    container_name: fitbit-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=fitbit_admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/fitbit_health.json
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  grafana_data:
