version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fitbit-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fitbit_user
      POSTGRES_PASSWORD: fitbit_pass
      POSTGRES_DB: fitbit_db
    volumes:
      - ./.db_data:/var/lib/postgresql/data
